
FROM bitnetdeps:latest

# We set the working directory to /app/Pipeline
WORKDIR /app/Pipeline

# Copy the requirements.txt file to the working directory
COPY ./Pipeline/requirements.txt .

# Install required Python packages for the pipeline
RUN pip install -r requirements.txt
