
FROM bitnetdeps:latest

WORKDIR /app

# Copy requirements
COPY ./Pipeline/requirements.txt .

# Install requirements in env (must use conda run)
RUN conda run -n BN pip install -r requirements.txt

# Copy the full project AFTER installing requirements
COPY . .
